apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  namespace: learn-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:    
      containers:
        - name: httpserver-container
          image: parvinshi/httpserver:v3-metrics
          envFrom:
          - configMapRef:
              name: httpserver-config
              optional: true
          resources:
            limits:
                cpu: 1000m
                memory: 1Gi
            requests:
                cpu: 100m
                memory: 100Mi
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo Execing the postStart handler"]
            preStop:
              exec:
                command: ["/bin/sh","-c","echo Execing the preStop handler; sleep 3"]
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              httpHeaders:
              - name: Liveness-Probe
                value: healthz
            initialDelaySeconds: 5
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  name: httpserver-svc
  namespace: learn-prometheus
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: httpserver
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpserver-config
  namespace: learn-prometheus
data:
  ADDR_PORT: "8080"
  LOG_LEVEL: ERROR
